### ISSUE TITLE
Add YAML format support

### ISSUE THREAD

**Issue by v-dem** [v-dem/queasy-config#26]

**Comment by Compolomus** [comment]
Ты хочешь свой парсер писать? Есть вариант замутить через расширение, но тогда зависимость появится от расширения
Под текущие реалии подогнать не сложно
https://www.php.net/manual/ru/function.yaml-parse.php

**Comment by v-dem** [comment]
Конечно нет, через расширение. Если надо, всегда можно сторонний парсер прикрутить. Мне главное чтоб в самом фреймворке не было зависимостей от других пакетов.

**Comment by v-dem** [comment]
There will be no support for YAML.
